version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: spacelist
    main: .
    binary: spacelist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: spacelist
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

homebrew_casks:
  - name: spacelist
    ids:
      - spacelist
    binaries:
      - spacelist
    homepage: "https://github.com/magicmark/spacelist"
    description: "A beautiful terminal UI for viewing all windows across your Aerospace window manager spaces"

    repository:
      owner: magicmark
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    caveats: |
      spacelist is now installed!

      Requirements:
        - Aerospace window manager must be installed

      Run 'spacelist' to start the application.
